### PR TITLE
Add GitHub Actions

### LINKED ISSUE #7: Do you want me to add GitHub Actions?
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

### PR DESCRIPTION
**Pull request by KTibow**
Closes #7, see https://KTibow/ha-blueprint#readme

### CODE REVIEW

**Comment by robmarkcole** [comment]
@KTibow what is the benefit of 
```
  schedule:
    - cron: '0 0 * * *'
```?

**Comment by KTibow** [comment]
If hassfest gets upgraded, if new syntax is now required, it'll let you know even if you haven't pushed for a while.

**Comment by robmarkcole** [comment]
ok great, thanks!

**Comment by robmarkcole** [comment]
@KTibow can you advise? 

image

**Comment by KTibow** [comment]
Yeah, just change the part where it says HACS/integration/action to HACS/action

**Comment by KTibow** [comment]
Do you think I should send out PRs to everyone to update it?

**Comment by robmarkcole** [comment]
@KTibow another error: `Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['ignore', 'category', 'repository']`

RE updates to everyone, sounds overkill to me, they would get the alerts already, but its your call!

**Comment by KTibow** [comment]
You don't need the github_token anymore. Just remove it.

**Comment by robmarkcole** [comment]
@KTibow not like this? https://github.com/robmarkcole/HASS-S3/actions/runs/381258568

**Comment by KTibow** [comment]
Add `ignore: [brands]` to the `with` stuff

**Comment by robmarkcole** [comment]
Another error https://github.com/robmarkcole/HASS-S3/actions/runs/381295208
Could you create a new PR to fix? Many thanks

**Comment by KTibow** [comment]
Really, I think that would be overkill. Just change `ignore` to all caps.

**Comment by robmarkcole** [comment]
Still failing

**Comment by KTibow** [comment]
Some repos fail randomly. For now just remove my action and follow HACS guidelines.

**Pull request merged**
